version: '2'
services: 
  db:
    container_name: feb_db_11
    image: postgres:11
    environment: 
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - feb-db-data:/var/lib/postgresql/data/pgdata 
  web:
    container_name: feb_odoo_12
    image: odoo:12
    depends_on: 
      - db
    ports: 
      - "$port:8069"
      - "$chat_port:8072"
    volumes: 
      - feb-web-data:/var/lib/odoo
      - ./docker:/etc/odoo/
      - ./addons:/mnt/extra-addons
volumes: 
  feb-web-data:
  feb-db-data: 
